### ISSUE TITLE
Calculated counts of each player type is always 0

### ISSUE THREAD

**Issue by esoccoli** [mroley1/Online-Grimoire#30]
I was working on fixing this, and what i found is that the 'option' function in the code takes a parameter being an array of character objects, and then the function iterates through that passed list and adds each character object from it to a locally defined array. However, for some reason, that locally scoped list is undefined even after the passed list is iterated through. I have also confirmed that the list passed in as a parameter (the one that is being iterated through), is defined and has valid data, but for some reason it cant be added to the locally scoped list. I dont exactly know whether this is the actual cause, but this is the only error in the console (and there are no warnings), and the characters everything else seems to work properly, so i am assuming that this is the cause.

**Comment by pikachu0542** [comment]
resolved by this commit: https://github.com/mroley1/Online-Grimoire/commit/bcc0f4000032b2632ea69261be6dac55cfb0f0ea
