### ISSUE TITLE
Token images are not standardized

### ISSUE THREAD

**Issue by MeMyselfMirai** [mroley1/Online-Grimoire#42]
BOTC has two sets of images: the official set of images that are used on the wiki, and an "unofficial" set of images used by the unofficial clocktower discord.

Currently, the tokens are a random combination of the two. The older tokens from the Base 3 scripts are mostly unofficial images, while the newer tokens rip the wiki and use the newer images. The disparity in detail is jarring:
![image](https://github.com/user-attachments/assets/e6e4383a-34a5-4f09-aa6b-4118dfc85d32)

We have 3 options:
- Make all images be official. This is fairly straightforward, by ripping the BOTC wiki. However, since this is an open-source project that can be found by anyone, TPI might get a bit annoyed that we are using their work. 
- Make all images be unofficial. I can ask the Unofficial clocktower discord for a zip file. However, these images are, technically speaking, of a lower quality. 
- Make our own images. Good luck with that. 

With the token refactoring, any of these options are a lot easier to pull off, as we don't need to regenerate the tokens.

**Comment by pikachu0542** [comment]
Would love to make them all the official images. Imo the new images look better, and all future characters will be released in the new style so might as well update to that now (+ i like consistency, lets make it consistent with the script tool)

**Comment by pikachu0542** [comment]
Resolved by #49
